pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'sudo mvn -B -DskipTests clean install package'
            }
        }
        stage('Test') {
            steps {
                sh 'sudo mvn test'
            }
        }
        stage('Deliver') {
            steps {
                sh 'sudo ./jenkins/scripts/deliver.sh'
            }
        }
    }
}
